
/*
 * @Author:Rajesh Srirangam,Rajesh.Srirangam@colorado.edu
 * @File Name:timer.h
 * @File Description:Used for LETIMER0 Initialisation
 * @Reference:David Sluiter Lecture 4,Lecture 5 Slides
 *
 */
#ifndef SRC_TIMERS_H_
#define SRC_TIMERS_H_

#include "app.h"
/*************MACROS**************/
#define LETIMER_ON_TIME_MS 175
#define LETIMER_PERIOD_MS 3000
//#define PRESCALER_VALUE 4
//#define ACTUAL_CLK_FREQ 32768/PRESCALER_VALUE // = 8192 Hz
//#define PRESCALER_VALUE_EM3 1
//#define ACTUAL_CLK_FREQ_EM3 1000/PRESCALER_VALUE_EM3
#define TICKS_MAX 65535
#define MICRO_SECONDS 1000000
/********************************/

#if (LOWEST_ENERGY_MODE==3)
#define PRESCALER_VALUE 1
#define ACTUAL_CLK_FREQ 1000/PRESCALER_VALUE
#endif
#if ((LOWEST_ENERGY_MODE==0)||(LOWEST_ENERGY_MODE==1)||(LOWEST_ENERGY_MODE==2))
#define PRESCALER_VALUE 4
#define ACTUAL_CLK_FREQ 32768/PRESCALER_VALUE // = 8192 Hz
#endif

#if (LOWEST_ENERGY_MODE==0)
//#define ACTUAL_CLK_PERIOD 1/ACTUAL_CLK_FREQ // = is it a floating point number or 0?
#define COMP0_VALUE_TO_LOAD (LETIMER_PERIOD_MS*ACTUAL_CLK_FREQ)/1000
//#define COMP1_VALUE_TO_LOAD ((COMP0_VALUE_TO_LOAD)-((LETIMER_ON_TIME_MS) * (COMP0_VALUE_TO_LOAD)/(LETIMER_PERIOD_MS)))
#endif
#if (LOWEST_ENERGY_MODE==1)
//#define ACTUAL_CLK_PERIOD 1/ACTUAL_CLK_FREQ // = is it a floating point number or 0?
#define COMP0_VALUE_TO_LOAD (LETIMER_PERIOD_MS*ACTUAL_CLK_FREQ)/1000
//#define COMP1_VALUE_TO_LOAD ((COMP0_VALUE_TO_LOAD)-((LETIMER_ON_TIME_MS) * (COMP0_VALUE_TO_LOAD)/(LETIMER_PERIOD_MS)))
#endif
#if (LOWEST_ENERGY_MODE==2)
//#define ACTUAL_CLK_PERIOD 1/ACTUAL_CLK_FREQ // = is it a floating point number or 0?
#define COMP0_VALUE_TO_LOAD (LETIMER_PERIOD_MS*ACTUAL_CLK_FREQ)/1000
//#define COMP1_VALUE_TO_LOAD ((COMP0_VALUE_TO_LOAD)-((LETIMER_ON_TIME_MS) * (COMP0_VALUE_TO_LOAD)/(LETIMER_PERIOD_MS)))
#endif
#if (LOWEST_ENERGY_MODE==3)
//#define ACTUAL_CLK_PERIOD_EM3 1/ACTUAL_CLK_FREQ_EM3 // = is it a floating point number or 0?
#define COMP0_VALUE_TO_LOAD (LETIMER_PERIOD_MS*ACTUAL_CLK_FREQ)/1000
//#define COMP1_VALUE_TO_LOAD ((COMP0_VALUE_TO_LOAD)-(((LETIMER_ON_TIME_MS) * (COMP0_VALUE_TO_LOAD))/(LETIMER_PERIOD_MS)))
#endif

void init_LETIMER0();

#endif /* SRC_TIMER_H_ */
